name: education_app
description: "Education Application project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  chewie: ^1.7.5
  dartz: ^0.10.1
  equatable: ^2.0.5
  file_picker: ^6.2.0
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.7
  iconly: ^1.0.1
  image_picker: ^1.0.7
  intl: ^0.18.1
  lottie: ^3.0.0
  open_file: ^3.3.2
  path_provider: ^2.1.2
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.6
  url_launcher: ^6.2.5
  youtube_metadata: ^1.0.1
  video_thumbnail: ^0.5.3
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  firebase_ui_auth: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  bloc_test: ^9.1.6
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0


flutter:
  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/images/
    - assets/lottie/
    - assets/icons/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
